swagger: '2.0'
info:
  $ref: ./info.yaml
# the domain of the service
host: inventaire.io
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /api
consumes:
  - application/json
produces:
  - application/json
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
tags:
  $ref: ./tags.yaml
