swagger: '2.0'
info:
  title: Inventaire API
  description: |
    **[inventaire.io](https://inventaire.io) HTTP API documentation**

    **Documentation status**: work in progress

    **API stability**: variably stable.

    Please let us know which endpoints you are relying on, and which need to get up the documentation priority list, by letting a message in [the dedicated issue](https://github.com/inventaire/inventaire/issues/29) (or, alternatively, in the [communication channel](https://wiki.inventaire.io/wiki/Communication-channels) of your choice), so that we have a clue of how noisy a breaking change has to be, ideally knowing namingly who should be noticed.

    Beside this documentation, diving into the code is always an option: everything starts in the [router](https://github.com/inventaire/inventaire/blob/master/server/controllers/routes.coffee), and is then delegated to the [controllers](https://github.com/inventaire/inventaire/tree/master/server/controllers).

    Then, feel welcome to [improve this documentation](https://github.com/inventaire/swagger-ui/tree/master/inv-spec)!

  version: "1.0.0"
# the domain of the service
host: inventaire.io
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /api
consumes:
  - application/json
produces:
  - application/json
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
tags:
  -
    name: Auth
    description: Login and stuffs
  -
    name: User
    description: Read and edit authentified user data
  -
    name: Items
    description: What users' inventories are made of
  -
    name: Entities
    description: Think books, authors, series data (see [entities map](https://inventaire.github.io/entities-map/))
  -
    name: Users
    description: Get/find other users data
  -
    name: Groups
    description: Read and edit users groups data
  -
    name: Transactions
    description: When users request each others items
